import { replaceInputCharactersUsingRegexAndConversionFunction } from './replaceInputCharactersUsingRegexAndConversionFunction';

export const convertInputToMorseCode = replaceInputCharactersUsingRegexAndConversionFunction(input);